# Generated by Django 2.0.5 on 2018-05-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastebin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paste',
            name='language',
            field=models.CharField(choices=[('python', 'Python'), ('ruby', 'Ruby'), ('c', 'C'), ('html', 'Html'), ('javascript', 'Javascript'), ('css', 'CSS'), ('txt', 'Text'), ('outros', 'Outros')], max_length=15),
        ),
    ]
